=== setl/verafied-java-core/src/main/resources/io/setl/bc/cw/credential_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Credential",
  "description": "A verifiable credential",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "@context",
    "credentialSubject",
    "issuer",
    "type"
  ],
  "properties": {
    "@context": {
      "description": "The JSON-LD context",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "credentialStatus": {
      "description": "Specification of a mechanism to test if this credential is still valid.",
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "id": {
          "type": "string",
          "format": "uri"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "credentialSubject": {
      "description": "The credential data",
      "type": "object"
    },
    "expirationDate": {
      "description": "The time at which this credential expires",
      "type": "string",
      "format": "date-time"
    },
    "id": {
      "description": "The unique identifier for this credential",
      "type": "string",
      "format": "uri"
    },
    "issuanceDate": {
      "description": "The time at which this credential was issued",
      "type": "string",
      "format": "date-time"
    },
    "issuer": {
      "description": "The issuer of this credential",
      "type": "string",
      "format": "uri"
    },
    "proof": {
      "description": "The cryptographic signature on this credential",
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "jws": {
          "description": "The Json Web Signature, if using a JWS style proof",
          "type": "string"
        },
        "type": {
          "description": "The type of proof",
          "type": "string"
        },
        "created": {
          "description": "The time at which this credential was signed",
          "type": "string",
          "format": "date-time"
        },
        "verificationMethod": {
          "description": "The public key in the DID which can be used to verify this proof",
          "type": "string",
          "format": "uri"
        },
        "salt": {
          "description": "Random data to ensure the document is unique",
          "type": "string"
        }
      }
    },
    "type": {
      "description": "Hierarchical specification of the credential type",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== setl/verafied-java-core/src/test/resources/io/setl/verafied/data/sample_vc_1.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1"
  ],
  "credentialStatus": {
    "id": "http://verafied.com/statusCheck/uuid:af08752f-831a-4776-8317-a1443a2aba6d",
    "recheckAfter": "PT24H",
    "type": "VerafiedHttpCheck"
  },
  "credentialSubject": {
    "@context": "http://schema.org/",
    "address": {
      "addressCountry": "USA",
      "addressLocality": "Rockbridge",
      "addressRegion": "California",
      "type": "PostalAddress"
    },
    "alternateName": "Arnie",
    "familyName": "Cunningham",
    "givenName": "Arnold",
    "id": "did:setl:xyz123",
    "owns": {
      "callSign": "Christine",
      "color": "Red and white",
      "dateVehicleFirstRegistered": "1958-02-14",
      "manufacturer": "Plymouth",
      "model": "Fury",
      "name": "CQB 241",
      "type": "Car",
      "vehicleIdentificationNumber": "D3MoNC4r"
    },
    "type": "Person"
  },
  "expirationDate": "2345-07-27T09:54:21.764461Z",
  "id": "uuid:8a8eb2dd-a9b5-4623-b7d1-e1ac206db070",
  "issuanceDate": "2021-07-27T09:54:21.762950Z",
  "issuer": "did:verafied:qDjni0qJX3KHrvgn46JBEVYE",
  "proof": {
    "created": "2021-11-04T16:11:52Z",
    "jws": "eyJhbGciOiJFUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..MEUCIFVxStB7PPIH_kTNQDQX3Yrb1M5-GgjIWJYXf6oJklufAiEA0RE7DsoQcMrgdXWHV6gpKkHixxQ4a2x0upQVR7BPpK8=",
    "salt": ">l<(CfQQm}<LrC-sA{&[%+OwP9XhEMmJO[Lkf $c",
    "type": "CanonicalJsonWithJws",
    "verificationMethod": "did:setl:qDjni0qJX3KHrvgn46JBEVYE#erGcvT"
  },
  "type": [
    "VerifiableCredential"
  ]
}
