=== setl/verafied-java-core/src/main/resources/io/setl/bc/cw/did_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Decentralized Identifier",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "assertionMethod": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "authentication": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capabilityDelegation": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capabilityInvocation": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "controller": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "created": {
      "type": "string",
      "format": "date-time"
    },
    "id": {
      "type": "string"
    },
    "updated": {
      "type": "string",
      "format": "date-time"
    },
    "verificationMethod": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/VerificationMethod"
      }
    },
    "@context": {
      "type": "array",
      "items": {
        "type": [
          "object",
          "string",
          "array",
          "null"
        ]
      }
    }
  },
  "definitions": {
    "VerificationMethod": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "publicKeyJwk": {
          "oneOf": [
            {
              "$ref": "#/definitions/PublicKeyJwkEc"
            },
            {
              "$ref": "#/definitions/PublicKeyJwkOkp"
            },
            {
              "$ref": "#/definitions/PublicKeyJwkRsa"
            }
          ]
        },
        "typ": {
          "type": "string"
        },
        "controller": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        }
      }
    },
    "PublicKeyJwkEc": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "kty": {
          "type": "string",
          "enum": [
            "ec"
          ],
          "default": "ec"
        },
        "kid": {
          "type": "string"
        },
        "use": {
          "type": "string"
        },
        "crv": {
          "type": "string"
        },
        "x": {
          "type": "string"
        },
        "y": {
          "type": "string"
        }
      },
      "title": "ec",
      "required": [
        "kty",
        "crv",
        "x",
        "y"
      ]
    },
    "PublicKeyJwkOkp": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "kty": {
          "type": "string",
          "enum": [
            "okp"
          ],
          "default": "okp"
        },
        "kid": {
          "type": "string"
        },
        "use": {
          "type": "string"
        },
        "crv": {
          "type": "string"
        },
        "x": {
          "type": "string"
        }
      },
      "title": "okp",
      "required": [
        "kty",
        "crv",
        "x"
      ]
    },
    "PublicKeyJwkRsa": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "kty": {
          "type": "string",
          "enum": [
            "rsa"
          ],
          "default": "rsa"
        },
        "kid": {
          "type": "string"
        },
        "use": {
          "type": "string"
        },
        "e": {
          "type": "string"
        },
        "n": {
          "type": "string"
        }
      },
      "title": "rsa",
      "required": [
        "kty",
        "e",
        "n"
      ]
    }
  }
}

=== setl/verafied-java-core/src/test/resources/io/setl/verafied/data/sample_did.json
{
  "@context": [
    "https://www.w3.org/ns/did/v1"
  ],
  "assertionMethod": [
    "did:setl:qDjni0qJX3KHrvgn46JBEVYE#erGcvT"
  ],
  "authentication": [
    "did:setl:qDjni0qJX3KHrvgn46JBEVYE#erGcvT"
  ],
  "capabilityDelegation": [],
  "capabilityInvocation": [],
  "controller": [
    "did:setl:qDjni0qJX3KHrvgn46JBEVYE"
  ],
  "created": "2020-07-17T12:20:45.800641Z",
  "id": "did:setl:qDjni0qJX3KHrvgn46JBEVYE",
  "updated": "2020-07-17T12:20:45.800641Z",
  "verificationMethod": [
    {
      "controller": [
        "did:setl:qDjni0qJX3KHrvgn46JBEVYE"
      ],
      "id": "did:setl:qDjni0qJX3KHrvgn46JBEVYE#erGcvT",
      "publicKeyJwk": {
        "crv": "P-256",
        "kid": "did:setl:qDjni0qJX3KHrvgn46JBEVYE#erGcvT",
        "kty": "ec",
        "use": "sig",
        "x": "LQcwZNTkPeZPluBQxam2gUGTKmB8DnkCX-IKofEmBfo=",
        "y": "cu0d1L9VXAVY58_f6A4lOEo_v5KBm39BVUjlERlMqKo="
      },
      "typ": "JwsVerificationKey2020"
    },
    {
      "controller": [
        "did:setl:qDjni0qJX3KHrvgn46JBEVYE"
      ],
      "id": "did:setl:qDjni0qJX3KHrvgn46JBEVYE#dummy",
      "publicKeyJwk": {
        "crv": "P-256",
        "kid": "did:setl:qDjni0qJX3KHrvgn46JBEVYE#erGcvT",
        "kty": "ec",
        "use": "sig",
        "x": "LQcwZNTkPeZPluBQxam2gUGTKmB8DnkCX-IKofEmBfo=",
        "y": "cu0d1L9VXAVY58_f6A4lOEo_v5KBm39BVUjlERlMqKo="
      },
      "typ": "JwsVerificationKey2020"
    }
  ]
}
